### ISSUE TITLE
翻译功能不能用啊

### ISSUE THREAD

**Issue by URGERKING** [manakanemu/bilibiliVtuberLiveTool#1]
如标题,用的火狐和油猴
一开始用的Tamper,结果也发现兼容,就是无法翻译,结果换油猴也是这样= =

**Comment by manakanemu** [comment]
抱歉之前没有测试火狐，我晚上去修复一下。

**Comment by URGERKING** [comment]
另外还装了Bilibili Evolved和Bilibili直播间挂机助手魔改,Bilibili港澳台

**Comment by manakanemu** [comment]
好的，多谢反馈

**Comment by manakanemu** [comment]
>如标题,用的火狐和油猴
一开始用的Tamper,结果也发现兼容,就是无法翻译,结果换油猴也是这样= = 

感谢您的反馈，看来这是一个广泛存在的问题，之前被我忽略了。问题原因是有道翻译的接口需要有道翻译的cookie，最快速的解决方案是直接打开[有道翻译页面](http://fanyi.youdao.com/?keyfrom=dict2.index)，随便翻译点什么，然后回到直播间刷新一下就可以正常使用翻译了。我会把这一点写入readme，在下一次更新时修复这个问题。
