### ISSUE TITLE
字幕显示有一定延迟

### ISSUE THREAD

**Issue by RIKR6735** [manakanemu/bilibiliVtuberLiveTool#2]
从评论发出到显示有两秒左右的延迟，这就很难受了，话都说完了才显示出来

**Comment by manakanemu** [comment]
请问您使用的是火狐浏览器么

**Comment by manakanemu** [comment]
就我所知火狐浏览器首次显示字幕可能会有延迟，但是只会出现在第一次捕获评论时，因为火狐的注入时机比较晚。  
这是脚本的[压力测试](https://github.com/manakanemu/bilibiliVtuberLiveTool/blob/master/web/press.gif)，理论上就算到达浏览器渲染极限，弹幕显示也是没有延迟的，所以按照目前您提供的信息我无法复现这个问题。

**Comment by RIKR6735** [comment]
> 请问您使用的是火狐浏览器么
是chrome

**Comment by RIKR6735** [comment]
嗯。。我仔细看了一下，发现同传man弹幕显示了才会显示，而不是评论发完直接显示出来
