### ISSUE TITLE
大佬求帮助，

### ISSUE THREAD

**Issue by KittyEar** [manakanemu/bilibiliVtuberLiveTool#3]
为什么在b站的直播间的输入框监听不到keydown事件，但是如果按数字可以监听到，按字母监听不到，我写了如下代码
$(document).keydown(function(event){
　　　　if(event.keyCode == 13){
　　　　　　alert('你按下了Enter'); 
　　　　}
});
另外，$('.chat-input.border-box').keydown(.........)也没有用，但是click可以，如果您有时间帮我瞧一瞧，如果没时间请无视我，打扰了，
![image](https://user-images.githubusercontent.com/57474949/100433471-1b0e7900-30d6-11eb-8264-0d66f5f6ddca.png)
![image](https://user-images.githubusercontent.com/57474949/100433638-501acb80-30d6-11eb-9264-9c9d72eb7a75.png)

**Comment by manakanemu** [comment]
抱歉我无法复现你的问题，我使用如下代码：
```
$(document).keydown(function(event){
    console.log(event.keyCode);
});
```
无论鼠标焦点在哪都能正常监听所有键盘事件，即使绑定在输入的textarea上，也能正常监听键盘。
浏览器是chrome 87.0.4280.67

**Comment by KittyEar** [comment]
谢谢回复，我解决了这个问题，是因为我写了两个$(document).keydown(function(event){


console.log(event.keyCode);});但是我又有新的问题了。$(window).on('keydown',function (e) {             if (e.which==13){                 console.log($('.chat-input.border-box').val());             }         });在直播间按完回车得不到我前面在textarea中输入的文字。多谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "manakanemu"<notifications@github.com&gt;; 
发送时间: 2020年11月27日(星期五) 晚上10:07
收件人: "manakanemu/bilibiliVtuberLiveTool"<bilibiliVtuberLiveTool@noreply.github.com&gt;; 
抄送: "【流浪~汗的宁&amp;静〗夜色"<2585290270@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [manakanemu/bilibiliVtuberLiveTool] 大佬求帮助， (#3)





 
抱歉我无法复现你的问题，我使用如下代码：
 $(document).keydown(function(event){     console.log(event.keyCode); });  
无论鼠标焦点在哪都能正常监听所有键盘事件，即使绑定在输入的textarea上，也能正常监听键盘。
 浏览器是chrome 87.0.4280.67

**Comment by manakanemu** [comment]
b站是用vue劫持鼠标点击事件的，它定义的keydown事件在监测到回车的时候会提交弹幕内容并且清空textarea，等他的keydown事件执行完了再执行你的keydown事件，自然就读不到东西了。如果你单纯就是想知道发送了什么，可以去读网站的vue变量，b站在聊天框上绑定了一个vue变量，用.lastdanmajku属性可以看到上一次发送了什么。

**Comment by manakanemu** [comment]
b站是用vue劫持事件的，它定义的keydown事件
```
 e.prototype.onKeyDown = function(t) {
            13 === t.keyCode && (t.preventDefault(),
            this.sendDanmaku(t).then(z.noop).catch(z.noop))
        }
```
在检测到回车的时候会提交弹幕内容并且清空textarea，等他的keydown事件执行完了再执行你的keydown事件，自然就读不到东西了。如果你单纯就是想知道发送了什么，可以去读网站的vue变量，b站在聊天框上绑定了一个vue变量，用.lastMsgContent属性可以看到上一次发送了什么。

**Comment by KittyEar** [comment]
好的，学到了。万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "manakanemu"<notifications@github.com&gt;; 
发送时间: 2020年11月27日(星期五) 晚上11:35
收件人: "manakanemu/bilibiliVtuberLiveTool"<bilibiliVtuberLiveTool@noreply.github.com&gt;; 
抄送: "【流浪~汗的宁&amp;静〗夜色"<2585290270@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [manakanemu/bilibiliVtuberLiveTool] 大佬求帮助， (#3)





 
b站是用vue劫持事件的，它定义的keydown事件
  e.prototype.onKeyDown = function(t) {             13 === t.keyCode &amp;&amp; (t.preventDefault(),             this.sendDanmaku(t).then(z.noop).catch(z.noop))         }  
在检测到回车的时候会提交弹幕内容并且清空textarea，等他的keydown事件执行完了再执行你的keydown事件，自然就读不到东西了。如果你单纯就是想知道发送了什么，可以去读网站的vue变量，b站在聊天框上绑定了一个vue变量，用.lastdanmajku属性可以看到上一次发送了什么。

**Comment by manakanemu** [comment]
客气，我平时没事儿也喜欢捣鼓捣鼓b站相关的js脚本，以后可以多交流。
