### ISSUE TITLE
自动捕获同传的弹幕？

### ISSUE THREAD

**Issue by taseikyo** [manakanemu/bilibiliVtuberLiveTool#4]
一般同传的弹幕都是【xxx】，那么是不是可以自动捕获？或者自己加正则的规则也行 :p

**Comment by manakanemu** [comment]
用正则匹配我是考虑过的，而且也有人是这么做的。不过最后我还是没加，因为这不够无脑，对计算机有一定要求。github不是论坛，greasyfork的社交做的也不好，我没法去给人解决这种使用上的问题。

我本人不太看直播，不太清楚同传man是不是都默认用中文方括号，是的话可以考虑加一个开关自动捕获。

**Comment by taseikyo** [comment]
我看过的基本都是【xxx】这种，加个自动捕获的开关最好了
btw，还以为写这个脚本的是个 DD 来着（

**Comment by manakanemu** [comment]
说是DD其实也没问题，不过我不会看特定的人。我是搜我自己喜欢的内容，谁播过就看看谁。

**Comment by taseikyo** [comment]
确实 我之前也是这种状态来着😂
总之很感谢这个脚本，希望早日加上自动补捕获的功能 :3
